spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/annuaire_db
spring.datasource.username=postgres
spring.datasource.password=admin1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true